### ISSUE TITLE
UpdateCapabilityToken exception.

### ISSUE THREAD

**Issue by cuiyuming** [twilio/twilio-client-quickstart-android#20]
Failed to remove account
                                                                          java.lang.IllegalArgumentException: Unknown account to delete
                                                                              at com.twilio.client.impl.useragent.UserAgent.deleteAccount(Native Method)
                                                                              at com.twilio.client.impl.CallControlManager.removeUserAccount(CallControlManager.java:371)
                                                                              at com.twilio.client.impl.CallControlManager.addUserAccount(CallControlManager.java:357)
                                                                              at com.twilio.client.impl.DeviceImpl.setCapabilityToken(DeviceImpl.java:240)
                                                                              at com.twilio.client.impl.DeviceImpl.updateCapabilityToken(DeviceImpl.java:274)

**Comment by tmconnors** [comment]
Hi @cuiyumingan can you please provide a little more information? Did this occurring during an active call or was the application in the background?

**Comment by khizar-lango** [comment]
I am facing same issue on following line of code 
 clientDevice = Twilio.createDevice(capabilityToken,deviceListener);
Can you please guide me how to fix it ?

**Comment by kbagchiGWC** [comment]
@khizar-lango what is issue? Can you share the details and logs?

**Comment by khizar-lango** [comment]
@kbagchiGWC  i got this exception 
Failed to remove account
java.lang.IllegalArgumentException: Unknown account to delete

on this line of code

clientDevice = Twilio.createDevice(capabilityToken,deviceListener);

**Comment by kbagchiGWC** [comment]
@khizar-lango are you using a valid account in the capabilityToken? Has this ever worked in the past? Please send the token your are using to kbagchi@twilio.com. 

What version of the CLIENT SDK are you using?
