### ISSUE TITLE
App crashes on x86_64 archictecture using emulator

### ISSUE THREAD

**Issue by tuckercr** [twilio/twilio-client-quickstart-android#46]
Hi, 

Not sure if this is the right place for this issue, please let me know if I should submit it elsewhere...

Since including the Twilio SDK in my project, my app crashes on startup when ran on a x86_64 emulator.  

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.thinkrite.assistant, PID: 2928
                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.thinkrite.assistant-1/base.apk"],nativeLibraryDirectories=[/data/app/com.thinkrite.assistant-1/lib/x86_64, /data/app/com.myapp.name-1/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libsupportjni.so"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at com.android.tools.profiler.support.ProfilerService.<clinit>(ProfilerService.java:44)
                      at com.android.tools.profiler.support.ProfilerService.initialize(ProfilerService.java:52)
                      at android.support.multidex.MultiDexApplication.<init>(MultiDexApplication.java:35)
                      at com.thinkrite.assistant.TraApplication.<init>(TraApplication.java:47)
                      at java.lang.Class.newInstance(Native Method)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

![image](https://cloud.githubusercontent.com/assets/6718800/26174715/44d706dc-3b1e-11e7-96dc-547c6c677254.png)

Regards,
Colin

**Comment by kbagchiGWC** [comment]
@tuckercr Thanks for filing the issue. We will take a look and notify you when this is fixed.

**Comment by idelgado** [comment]
Given that the error references `libsupportjni.so`, which is not something we ship with the Voice library, I suspect this is an emulator configuration or emulator image problem.

**Comment by tuckercr** [comment]
The problem was due to an Run/Debug Configuration setting "enable advanced profiling"

I turned this off and the problem went away.

**Comment by tuckercr** [comment]
![image](https://cloud.githubusercontent.com/assets/6718800/26459695/52744e9e-4145-11e7-9e2c-1d05c1bec75a.png)

**Comment by kbagchiGWC** [comment]
@tuckercr I am glad that you resoled the problem.
