### ISSUE TITLE
Token does not allow outgoing calls

### ISSUE THREAD

**Issue by SanjayAndroidDev** [twilio/twilio-client-quickstart-android#48]
I can't make a call after successful register. Here my logcat.

E/client.twilio.com.quickstart.ClientActivity: Connection error: Connection declined:Token does not allow outgoing callsE/Connection: Connecting call failed              java.lang.IllegalArgumentException: From name cannot be null when making a call                  at com.twilio.client.impl.MakeCallCommand.(MakeCallCommand.java:34)                  at com.twilio.client.impl.CallControlManager.makeCall(CallControlManager.java:402)                  at com.twilio.client.impl.InternalConnectionImpl.connect(InternalConnectionImpl.java:266)                  at com.twilio.client.impl.DeviceImpl$3.onCompletion(DeviceImpl.java:305)                  at com.twilio.client.impl.MediaManager.onPlayComplete(MediaManager.java:174)                  at com.twilio.client.impl.sound.SoundPoolPlayThread.onPeriodicNotification(SoundPoolPlayThread.java:228)                  at android.media.AudioTrack$NativeEventHandlerDelegate$1.handleMessage(AudioTrack.java:1583)                  at android.os.Handler.dispatchMessage(Handler.java:102)                  at android.os.Looper.loop(Looper.java:211)                  at android.app.ActivityThread.main(ActivityThread.java:5371)                  at java.lang.reflect.Method.invoke(Native Method)                  at java.lang.reflect.Method.invoke(Method.java:372)                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)

**Comment by kbagchiGWC** [comment]
@SanjayAndroidDev can you check your capability token and make sure your capability token included outgoing capability? You can find details on how to create a capability token [here](https://www.twilio.com/docs/api/client/capability-tokens). If your capability token includes outgoing capability, `Device.Capability. OUTGOING` will be set to `true`. 

If you need us to look at the capability token, please open a support ticket [here](https://support.twilio.com/hc/en-us/requests/new ) and provide the token you are using. Once you have a ticket number post it here and we'll follow up.

**Comment by kbagchiGWC** [comment]
@SanjayAndroidDev we strongly suggest you to use our next generation `Voice SDK`. I have noticed you opened an issue for Voice SDK https://github.com/twilio/voice-quickstart-android/issues/86. Please let us know if that is still an issue and if you need help.

**Comment by kbagchiGWC** [comment]
Closing it due to no activity for a while.

**Comment by roshannsharma** [comment]
Call Error: 31201, Authorization error

**Comment by kbagchiGWC** [comment]
@UjjavalMoradiya 
Do you have a CallSid that resulted in `603`? What version of the SDK are you using?

**Comment by mobilekbs** [comment]
Hello thread,

I am getting the following error while making a call:

Connection error: Connection declined:Token does not allow outgoing calls

---
 java.lang.IllegalArgumentException: From name cannot be null when making a call
        at com.twilio.client.impl.MakeCallCommand.<init>(MakeCallCommand.java:34)
        at com.twilio.client.impl.CallControlManager.makeCall(CallControlManager.java:402)
        at com.twilio.client.impl.InternalConnectionImpl.connect(InternalConnectionImpl.java:266)
        at com.twilio.client.impl.DeviceImpl$3.onCompletion(DeviceImpl.java:305)
        at com.twilio.client.impl.MediaManager.onPlayComplete(MediaManager.java:174)
        at com.twilio.client.impl.sound.SoundPoolPlayThread.onPeriodicNotification(SoundPoolPlayThread.java:228)
        at android.media.AudioTrack$NativePositionEventHandlerDelegate$1.handleMessage(AudioTrack.java:2927)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

----

I have followed each step provided in the Quick-start guide. This is working for iOS but in ANdroid, I am getting this error.

Can you suggest and provide me some direction?

Thank you

**Comment by kbagchiGWC** [comment]
Hi @mobilekbs 

To be able to make outgoing calls, your capability token needs to have an app sid. You will be able find details on this [here](https://www.twilio.com/docs/voice/client/capability-tokens#allow-outgoing-connections).

Looks like you are using 1.X SDK. This version of the SDKs have been deprecated and superseded by the [Programmable Voice SDKs](https://www.twilio.com/docs/voice/voip-sdk). You will find the deprecation notice - https://www.twilio.com/docs/voice/client/android and https://github.com/twilio/twilio-client-quickstart-android. Please move to our [latest SDKs](https://www.twilio.com/docs/voice/voip-sdk/android) and let us know if you need help.

**Comment by slowas** [comment]
I'am gave same issue some times get error "Token does not allow outgoing calls."

**Comment by kbagchiGWC** [comment]
@slowas what version of the SDK are you using? 2.X and 3.X(currently in beta, soon to be GA) do not use Capability Token. I would suggest you to migrate to 2.x or 3.X. Reach out to us if you have issues with the migration.

**Comment by slowas** [comment]
@kbagchiGWC Sorry, i writed in wrong repository. Problem with PHP sdk, i created issue there.
