### ISSUE TITLE
Android SDK - Connection error: Connection declined:Token does not allow outgoing calls

### ISSUE THREAD

**Issue by KerryTucker** [twilio/twilio-client-quickstart-android#64]
i am getting Json Web Token(JWT) successfully in Android App but did not make call normally as well as with twiml
whenever i touch on phone icon & dial number it shows me this error

**Error:**
```
07-16 12:44:10.549 17084-17084/com.twilio.client.quickstart E/client.twilio.com.quickstart.ClientActivity: Connection error: Connection declined:Token does not allow outgoing calls
07-16 12:44:10.553 17084-17084/com.twilio.client.quickstart E/Connection: Connecting call failed
                                                                          java.lang.IllegalArgumentException: From name cannot be null when making a call
                                                                              at com.twilio.client.impl.MakeCallCommand.<init>(MakeCallCommand.java:34)
                                                                              at com.twilio.client.impl.CallControlManager.makeCall(CallControlManager.java:402)
                                                                              at com.twilio.client.impl.InternalConnectionImpl.connect(InternalConnectionImpl.java:266)
                                                                              at com.twilio.client.impl.DeviceImpl$3.onCompletion(DeviceImpl.java:305)
                                                                              at com.twilio.client.impl.MediaManager.onPlayComplete(MediaManager.java:174)
                                                                              at com.twilio.client.impl.sound.SoundPoolPlayThread.onPeriodicNotification(SoundPoolPlayThread.java:228)
                                                                              at android.media.AudioTrack$NativeEventHandlerDelegate$1.handleMessage(AudioTrack.java:1286)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5086)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                              at dalvik.system.NativeStart.main(Native Method)
```
i submitted ticket & give him my JWT as well as Account SID here is my Ticket No.: **1433486**

**Comment by idelgado** [comment]
Please follow the quickstart guide at https://github.com/twilio/voice-quickstart-android. This version of the SDK is deprecated as stated in the README.
